<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>TinyBrain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="tiny-fp" Version="2.1.0" />
    <PackageReference Include="System.Numerics.Tensors" Version="9.*" />
  </ItemGroup>
  
</Project>
